// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	entity "github.com/abmid/icanvas-analytics/pkg/canvas/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDiscussionRepository is a mock of DiscussionRepository interface
type MockDiscussionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDiscussionRepositoryMockRecorder
}

// MockDiscussionRepositoryMockRecorder is the mock recorder for MockDiscussionRepository
type MockDiscussionRepositoryMockRecorder struct {
	mock *MockDiscussionRepository
}

// NewMockDiscussionRepository creates a new mock instance
func NewMockDiscussionRepository(ctrl *gomock.Controller) *MockDiscussionRepository {
	mock := &MockDiscussionRepository{ctrl: ctrl}
	mock.recorder = &MockDiscussionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDiscussionRepository) EXPECT() *MockDiscussionRepositoryMockRecorder {
	return m.recorder
}

// ListDiscussionByCourseID mocks base method
func (m *MockDiscussionRepository) ListDiscussionByCourseID(courseID uint32) ([]entity.Discussion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDiscussionByCourseID", courseID)
	ret0, _ := ret[0].([]entity.Discussion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDiscussionByCourseID indicates an expected call of ListDiscussionByCourseID
func (mr *MockDiscussionRepositoryMockRecorder) ListDiscussionByCourseID(courseID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDiscussionByCourseID", reflect.TypeOf((*MockDiscussionRepository)(nil).ListDiscussionByCourseID), courseID)
}
