// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	entity "github.com/abmid/icanvas-analytics/pkg/canvas/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAssigmentRepository is a mock of AssigmentRepository interface
type MockAssigmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAssigmentRepositoryMockRecorder
}

// MockAssigmentRepositoryMockRecorder is the mock recorder for MockAssigmentRepository
type MockAssigmentRepositoryMockRecorder struct {
	mock *MockAssigmentRepository
}

// NewMockAssigmentRepository creates a new mock instance
func NewMockAssigmentRepository(ctrl *gomock.Controller) *MockAssigmentRepository {
	mock := &MockAssigmentRepository{ctrl: ctrl}
	mock.recorder = &MockAssigmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAssigmentRepository) EXPECT() *MockAssigmentRepositoryMockRecorder {
	return m.recorder
}

// ListAssigmentByCourseID mocks base method
func (m *MockAssigmentRepository) ListAssigmentByCourseID(CourseID uint32) ([]entity.Assigment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAssigmentByCourseID", CourseID)
	ret0, _ := ret[0].([]entity.Assigment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAssigmentByCourseID indicates an expected call of ListAssigmentByCourseID
func (mr *MockAssigmentRepositoryMockRecorder) ListAssigmentByCourseID(CourseID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAssigmentByCourseID", reflect.TypeOf((*MockAssigmentRepository)(nil).ListAssigmentByCourseID), CourseID)
}
