// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	entity "github.com/abmid/icanvas-analytics/pkg/canvas/entity"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockEnrollRepository is a mock of EnrollRepository interface
type MockEnrollRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEnrollRepositoryMockRecorder
}

// MockEnrollRepositoryMockRecorder is the mock recorder for MockEnrollRepository
type MockEnrollRepositoryMockRecorder struct {
	mock *MockEnrollRepository
}

// NewMockEnrollRepository creates a new mock instance
func NewMockEnrollRepository(ctrl *gomock.Controller) *MockEnrollRepository {
	mock := &MockEnrollRepository{ctrl: ctrl}
	mock.recorder = &MockEnrollRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEnrollRepository) EXPECT() *MockEnrollRepositoryMockRecorder {
	return m.recorder
}

// ListEnrollmentByCourseID mocks base method
func (m *MockEnrollRepository) ListEnrollmentByCourseID(courseID uint32) ([]entity.Enrollment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnrollmentByCourseID", courseID)
	ret0, _ := ret[0].([]entity.Enrollment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnrollmentByCourseID indicates an expected call of ListEnrollmentByCourseID
func (mr *MockEnrollRepositoryMockRecorder) ListEnrollmentByCourseID(courseID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnrollmentByCourseID", reflect.TypeOf((*MockEnrollRepository)(nil).ListEnrollmentByCourseID), courseID)
}
