// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	entity "github.com/abmid/icanvas-analytics/internal/report/entity"
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockReportEnrollmentUseCase is a mock of ReportEnrollmentUseCase interface
type MockReportEnrollmentUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockReportEnrollmentUseCaseMockRecorder
}

// MockReportEnrollmentUseCaseMockRecorder is the mock recorder for MockReportEnrollmentUseCase
type MockReportEnrollmentUseCaseMockRecorder struct {
	mock *MockReportEnrollmentUseCase
}

// NewMockReportEnrollmentUseCase creates a new mock instance
func NewMockReportEnrollmentUseCase(ctrl *gomock.Controller) *MockReportEnrollmentUseCase {
	mock := &MockReportEnrollmentUseCase{ctrl: ctrl}
	mock.recorder = &MockReportEnrollmentUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockReportEnrollmentUseCase) EXPECT() *MockReportEnrollmentUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockReportEnrollmentUseCase) Create(ctx context.Context, reportEnroll *entity.ReportEnrollment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, reportEnroll)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockReportEnrollmentUseCaseMockRecorder) Create(ctx, reportEnroll interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReportEnrollmentUseCase)(nil).Create), ctx, reportEnroll)
}

// Read mocks base method
func (m *MockReportEnrollmentUseCase) Read(ctx context.Context) ([]entity.ReportEnrollment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ctx)
	ret0, _ := ret[0].([]entity.ReportEnrollment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read
func (mr *MockReportEnrollmentUseCaseMockRecorder) Read(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockReportEnrollmentUseCase)(nil).Read), ctx)
}

// Update mocks base method
func (m *MockReportEnrollmentUseCase) Update(ctx context.Context, reportEnroll *entity.ReportEnrollment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, reportEnroll)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockReportEnrollmentUseCaseMockRecorder) Update(ctx, reportEnroll interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockReportEnrollmentUseCase)(nil).Update), ctx, reportEnroll)
}

// Delete mocks base method
func (m *MockReportEnrollmentUseCase) Delete(ctx context.Context, reportEnrollID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, reportEnrollID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockReportEnrollmentUseCaseMockRecorder) Delete(ctx, reportEnrollID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockReportEnrollmentUseCase)(nil).Delete), ctx, reportEnrollID)
}

// CreateOrUpdateByFilter mocks base method
func (m *MockReportEnrollmentUseCase) CreateOrUpdateByFilter(ctx context.Context, filter entity.ReportEnrollment, assigment *entity.ReportEnrollment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateByFilter", ctx, filter, assigment)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateByFilter indicates an expected call of CreateOrUpdateByFilter
func (mr *MockReportEnrollmentUseCaseMockRecorder) CreateOrUpdateByFilter(ctx, filter, assigment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateByFilter", reflect.TypeOf((*MockReportEnrollmentUseCase)(nil).CreateOrUpdateByFilter), ctx, filter, assigment)
}

// FindFilter mocks base method
func (m *MockReportEnrollmentUseCase) FindFilter(ctx context.Context, filter entity.ReportEnrollment) ([]entity.ReportEnrollment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFilter", ctx, filter)
	ret0, _ := ret[0].([]entity.ReportEnrollment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFilter indicates an expected call of FindFilter
func (mr *MockReportEnrollmentUseCaseMockRecorder) FindFilter(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFilter", reflect.TypeOf((*MockReportEnrollmentUseCase)(nil).FindFilter), ctx, filter)
}
